version = 0.1

default-task = 'build'

extensions = ['chomp@0.1:npm', './static-site-generator.js']

[server]
root = "public_html"

[[task]]
name = 'copy:css'
targets = ['public_html/codemirror.css', 'public_html/lint.css']
invalidation = 'always'
run = '''
  curl "https://ga.jspm.io/npm:codemirror@5" -o codemirror.version
  curl "https://ga.jspm.io/npm:codemirror@$(cat codemirror.version)/lib/codemirror.css" -o public_html/codemirror.css
  curl "https://ga.jspm.io/npm:codemirror@$(cat codemirror.version)/addon/lint/lint.css" -o public_html/lint.css
  rm codemirror.version
'''

[[task]]
name = 'generate:static'
template = 'static-site-generator'
[task.template-options]
template = 'template.html'
pages = 'pages'
public-html = 'public_html'
feed = 'feed.json'
feed-exclude = ['pages/docs/', 'pages/index.md']
site-name = 'jspm.org'
site-url = 'https://jspm.org/'
site-image = 'https://jspm.org/jspm.png'
edit-url = 'https://github.com/jspm/jspm.org/blob/master'

[[task]]
name = 'fetch:cli'
run = '''
  curl https://raw.githubusercontent.com/jspm/jspm/main/docs/cli.md > pages/docs/cli.md
'''

[[task]]
name = 'docs:cli'
deps = ['fetch:cli']
targets = ['./pages/docs/cli.md']
engine = 'node'
run = '''
  // add the following text to the beginning of cli.md file
  import fs from 'fs';
  const cli = fs.readFileSync('./pages/docs/cli.md', 'utf8');
  const content = `+++
title = "JSPM CLI - Documentation"
description = "JSPM CLI Documentation"
next-section = "teleporthq-sponsorship"
prev-section = "docs/api"
+++

`
  fs.writeFileSync('./pages/docs/cli.md', content + cli);
'''

[[task]]
name = 'build'
deps = ['copy:css', 'docs:cli', 'generate:static']

[[task]]
name = 'excalidraw-to-svg'
run = 'node ./architecture/excalidraw-to-svg.js'

[[task]]
name = 'serve-architecture'
run = 'npx http-server ./architecture -c-1'
